### PR TITLE
spark/databricks: out-of-catalog schema enumeration

### PR DESCRIPTION
**Pull request by detule**
Fixes https://github.com/r-dbi/odbc/issues/613

Screenshot 2023-10-25 at 11 16 59 PM

### CODE REVIEW

**Comment by edgararuiz** [comment]
Hi, can I control the Catalog it will show me the tables for?  I added `Catalog="main"` to the connection arguments, but it didn't show me any tables, and it still showed the schema/tables for `samples`

```r
library(DBI)
con <- dbConnect(
  odbc::odbc(),
  Driver = "/Library/simba/spark/lib/libsparkodbc_sb64-universal.dylib",
  Host = "[posit url]",
  Port = 443,
  AuthMech = 3,
  HTTPPath = "/sql/1.0/warehouses/300bd24ba12adf8e",
  Protocol = "https",
  ThriftTransport = 2,
  SSL = 1,
  UID = "token",
  PWD = Sys.getenv("DATABRICKS_TOKEN"),
  Catalog = "main"
  )
```


Screenshot 2023-10-26 at 1 57 51 PM

**Comment by detule** [comment]
Hey Edgar:

Thanks for checking it out!  Looks like schemas are now enumerated correctly, but you have stumbled across tables within some schemas being listed inconsistently.

Not entirely sure what's going on - do you have the ability to create another catalog and populate it with some sample data? Trying to figure out if it is a permission issue / `main` being somehow special.  Or maybe something specific to `information_schema` ( since i think `default` is actually empty in this case ).

I don't think I have `CREATE CATALOG` permissions / can't try it myself.

**Comment by edgararuiz** [comment]
Hi @detule , maybe this connection needs a custom `odbcConnectionTables` method? I'm able to access the tables by passing the full path of the catalog/schema

```r
dbGetQuery(con, "show schemas in main")
#>         databaseName
#> 1            default
#> 2 information_schema
dbGetQuery(con, "show tables in main.information_schema")
#>              database                       tableName isTemporary
#> 1  information_schema              catalog_privileges       FALSE
#> 2  information_schema                    catalog_tags       FALSE
#> 3  information_schema                        catalogs       FALSE
#> 4  information_schema               check_constraints       FALSE

```

**Comment by detule** [comment]
Hi Edgar - maybe.

Can we verify that 'main' is the only catalog that is misbehaving?

**Comment by edgararuiz** [comment]
`main` seems to be working fine when accessed via passing the full path in the SQL, that's why I think that it needs a custom `odbcConnectionTables` method

**Comment by detule** [comment]
Thanks Edgar.

Before we go ahead and write custom methods - do you have a way of verifying whether enumerating tables with the existing code works fine away from 'main'?

Trying to figure out if this is an issue with the driver that we can raise with the vendor.

**Comment by edgararuiz** [comment]
Yeah, I tried it with `samples`, and it worked fine:

```r
dbGetQuery(con, "show schemas in samples")
#>   databaseName
#> 1      default
#> 2      nyctaxi
#> 3         tpch
dbGetQuery(con, "show tables in samples.nyctaxi")
#>   database tableName isTemporary
#> 1  nyctaxi     trips       FALSE
```

**Comment by detule** [comment]
Thanks - I did some tresting as well away from `main`: current methods to enumerate schema and tables _seem_ to work fine.  Below, see both the `hive_metastore` and `samples` catalogs, and tables within them listed correctly.

Screenshot 2023-10-28 at 9 58 44 PM

@hadley I think let's:

A.  Merge this PR that fixes enumerating schemas - this is a legitimate issue with our code. 
B.  Not being able to enumerate tables using existing methods - if it is isolated to `main` this seems like maybe an issue with the driver, and we should maybe raise with the vendor.  At any rate, if there is urgency to fix here in the near term, we can maybe write a special case for DataBricks + catalog == `main` in a separate PR.

**Comment by detule** [comment]
Not quite a reprex, but this is the output from the integrated query log:

Screenshot 2023-11-01 at 5 48 39 PM

Lower three queries are all calls to [`SQLTables`](https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqltables-function?view=sql-server-ver16) with us varying the TableType parameter ( from `TABLE` to `VIEW` to `SYSTEM VIEW` - driver interprets all as `NULL` ).  We retrieved no results from any of those calls.  The top query is a call to `SQLTables` away from the `main` catalog.

**Review by hadley — APPROVED** [review]

**Pull request merged**
