### PR TITLE
Encode non-ASCII Column Names to UTF-8

### LINKED ISSUE #430: The Encoding of the column names is not UTF-8
### Issue Description and Expected Result

When the SQL contains non-ASCII strings as the field names, the returned **column names** of the data.frame is not encoded as UTF-8.

### Database

SQL Server 2014 

### Reproducible Example

Example:
```r
library(odbc)
library(DBI)
con <- dbConnect(odbc::odbc(), dsn = "SQL Server")
x <- DBI::dbGetQuery(con, "select '汉语' as 中文")
Encoding(x[[1]]) # returns UTF-8
Encoding(colnames(x)) # returns unknown and are actually not UTF-8 encoded
```

image

### LINKED ISSUE #432: Garbage error message when the encodings of the server and client are different
### Issue Description and Expected Result

When the database's encoding is GBK, the client's encoding is UTF-8 and the SQL contains non-ASCII letters, the error message becomes garbage letters.

The reason is that odbc converts the SQL to the encoding of the Database first. Thus, when nanodbc throw errors, if the error message contains the SQL string, the encoding of the error message is the same as the database, which differs from the encoding of the Client. 

Thus, the error message displayed on the client becomes garabage.

The fix I believe is to convert the encoding of the error message to the client's encoding.

### Database

MS SQL Server 2014

### Reproducible Example

- A database with encoding other than UTF-8, e.g., GBK
- A client (the user machine) uses encoding UTF-8
- A SQL with non-ASCII letters

```r
con <- DBI::dbConnect(odbc::odbc(), drv = "SQL Server", encoding = "GBK", ...)
sql <- "select '中文' from 汉语"
# this is garabage message
DBI::dbGetQuery(con, sql)
# this fixes the message
tryCatch(DBI::dbGetQuery(con, sql), error = function(e) stop(iconv(e$message, "GBK", "UTF-8")))
```

image

### PR DESCRIPTION
**Pull request by detule**
Closes #430
Closes #432

This is a rebase of #431 - details there.

Thanks @shrektan.

### CODE REVIEW

**Comment by hadley** [comment]
What do we need to do to get this merged?

**Comment by hadley** [comment]
@shrektan could you please take a quick look so we can get this into odbc?

**Comment by shrektan** [comment]
It looks good to me.

**Review by shrektan — APPROVED** [review]
looks good to me.

**Comment by simonpcouch** [comment]
From what I can tell in public comments, this PR is ready to merge. cc @hadley

**Pull request merged**
