### PR TITLE
Use USER expression to retrieve current username on Oracle

### LINKED ISSUE #738: Empty `con@info$username`
_(I am absolutely not sure if it is a bug or if it is expected; sorry if it is not.)_

I needed my user name so I tried `con@info$username` but it is empty.
However it is used e.g. in
https://github.com/r-dbi/odbc/blob/e8b68fa5de44bf3d3cd7cfedb204bf8f7c260f16/R/driver-oracle.R#L53
and in
https://github.com/r-dbi/odbc/blob/e8b68fa5de44bf3d3cd7cfedb204bf8f7c260f16/R/driver-oracle.R#L108

<details>
### Database

```r
dbGetInfo(con)
# $dbname
# [1] ""
# 
# $dbms.name
# [1] "Oracle"
# 
# $db.version
# [1] "19.00.0000"
# 
# $username
# [1] ""
# 
# $host
# [1] ""
# 
# $port
# [1] ""
# 
# $sourcename
# [1] "xxx"
# 
# $servername
# [1] "xxx"
# 
# $drivername
# [1] "RStudio Oracle ODBC Driver"
# 
# $odbc.version
# [1] "03.52"
# 
# $driver.version
# [1] "2.0.2.1002"
# 
# $odbcdriver.version
# [1] "03.80"
# 
# $supports.transactions
# [1] TRUE
# 
# $getdata.extensions.any_column
# [1] TRUE
# 
# $getdata.extensions.any_order
# [1] TRUE
# 
# attr(,"class")
# [1] "Oracle"      "driver_info" "list"   
```
</details>

```r
library(DBI)
con <- dbConnect(odbc::odbc(), dsn = "xxx")
con@info$username
# [1] ""
```

<details>
<summary>Session Info</summary>

```r
sessionInfo()
# R version 4.1.2 (2021-11-01)
# Platform: x86_64-pc-linux-gnu (64-bit)
# Running under: Red Hat Enterprise Linux Server 7.8 (Maipo)
# 
# Matrix products: default
# BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so
# 
# locale:
#  [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
#  [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
#  [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
# 
# attached base packages:
# [1] stats     graphics  grDevices datasets  utils     methods   base     
# 
# other attached packages:
# [1] DBI_1.0.0
# 
# loaded via a namespace (and not attached):
#  [1] bit_1.1-14      odbc_1.3.5      compiler_4.1.2  ellipsis_0.3.2  hms_1.1.1       tools_4.1.2     Rcpp_1.0.7      bit64_0.9-7    
#  [9] vctrs_0.3.8     blob_1.2.2      lifecycle_1.0.1 pkgconfig_2.0.2 rlang_0.4.12   
```
</details>

### PR DESCRIPTION
**Pull request by hadley**
Fixes #738

@ThomasSoeiro would you mind trying this out? I think the easiest way to exercise the code is to run `DBI::dbListTables(con)`, where `con` is a connection to an Oracle database.

### CODE REVIEW

**Comment by detule** [comment]
Nice work!  What do you think about specializing `dbGetInfo` for `Oracle`.  Something like
```
res <- callNextMethod()
if ( res$username == "" ) {
  res$username <- dbGetQuery(conn, "SELECT USER FROM DUAL")$USER
}
return(res)
```
We can then modify `OdbcConnection` so that the static info object is also populated correctly `conn@info <- dbGetInfo(conn)`.

**Comment by ThomasSoeiro** [comment]
@hadley 

Only my IT department can install packages on our server (and they probably won't install a dev version).

I simply tried pasting the new fonction but I got:
```
Erreur dans setMethod("odbcConnectionTables", c("Oracle", "character"), function(conn,  : 
  no existing definition for function ‘odbcConnectionTables’
```

Is there a way I can test without installing the dev version?

Thanks!

NOTE: `DBI::dbListTables(con)` currently works as expected despite empty `con@info$username`.

**Comment by hadley** [comment]
@detule in principle that would be fine, but I'm not sure much actually needs the active user name and tweaking the SQL here definitely seems simpler.

@ThomasSoeiro no worries, we'll figure out how to test ourselves.

**Comment by detule** [comment]
Sounds good @hadley

Tested your changes on my `Oracle 21` instance by clearing out the `username` slot on my connection (info) object.  Seems to work as expected.

```
> odbc:::odbcConnectionTables(conn)
  table_catalog table_schema  table_name table_type table_remarks
1          <NA>           SA mtcars_test      TABLE          <NA>
2          <NA>           SA          DF      TABLE          <NA>
...
> head(odbc:::odbcConnectionTables(conn, schema_name="SA"), n = 2)
  table_catalog table_schema  table_name table_type table_remarks
1          <NA>           SA mtcars_test      TABLE          <NA>
2          <NA>           SA          DF      TABLE          <NA>
> head(odbc:::odbcConnectionTables(conn, schema_name="SYSTEM"), n = 2)
  table_catalog table_schema             table_name table_type table_remarks
1          <NA>       SYSTEM LOGMNR_SESSION_EVOLVE$      TABLE          <NA>
2          <NA>       SYSTEM         LOGMNR_GLOBAL$      TABLE          <NA>
> conn@info$username
[1] ""
```

**Review by detule — APPROVED** [review]

**Pull request merged**
