### PR TITLE
fix a missing comma in odbc_write_table()

### LINKED ISSUE #319: after #313 dbWriteTable() is case-sensitive in terms of columns
After PR #313 (7c4bc6ec) being merged, the `dbWriteTable()` method is now case-sensitive in terms of matching columns agains the db table. But before this PR, it's case insensitive (at least for MSSQLServer). This breaks many of my R scripts...

The database version is:

```
Microsoft SQL Server 2014 - 12.0.2000.8 (X64) 
	Feb 20 2014 20:04:26 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: )
```

## The example code

(Before the PR, it runs successfully without errors. )

``` r
conn <- DBI::dbConnect(...)
DBI::dbExecute(conn, "create table test (aaa int) ")
#> [1] 0
DBI::dbWriteTable(conn, 'test', value = data.frame(AAA = 1L), append = TRUE)
### I have to change `data.frame(AAA = 1L)` to ` data.frame(aaa = 1L)`. ###
#> Error in result_describe_parameters(rs@ptr, fieldDetails): Index out of bounds: [index='param_index'].
DBI::dbExecute(conn, "drop table test")
#> Warning in new_result(connection@ptr, statement): Cancelling previous query
#> [1] 0
DBI::dbDisconnect(conn)
```

### PR DESCRIPTION
**Pull request by shrektan**
Fixes #319

### CODE REVIEW

**Comment by jimhester** [comment]
Whether case sensitivity matters is database dependent, some databases it doesn't matter, some it does and in some it matters dependant on a configuration parameter. We can't assume case insensitivity in the odbc package.

**Comment by jimhester** [comment]
But maybe we have to do this, I am not sure why we are getting case mismatches when describing the columns...

**Comment by detule** [comment]
The first commit is a bugix (sorry!).  

Presumably with that commit only, if there is a case mismatch between the columns of `values` and the target table the fallback should continue to work gracefully.

@shrektan does that work?

**Comment by detule** [comment]
Having said that, the entirety of the PR, including the fuzzy (case) matching on the [R] side is probably a good idea.

Nice work.

**Comment by shrektan** [comment]
I think we may need to provide the column name argument when calling odbcConnectionColumns(conn, name) and let the databases verify if the fields provided can be matched or not. I will tweak and verify my “theory” later.

**Comment by shrektan** [comment]
@detule You are right. Fix `details[!is.na(details$param_index), ]` only is enough for this case, in fact. 

Regarding to fieldDetails, the only robust way I can think of is to call odbcConnectionColumns() and let the server to find the correct columns. 

However, this approach has a drawback that `catalog::columns catalog::find_columns()` can only handle scalar column_name, so we have to call the function multiple times, which may result in some performance overheads when there're many fields in the table (). The code will be like this:

```r
      # the cpp function connection_sql_columns() now is only able to handle
      # scalar column_name.
      details <- lapply(names(values), function(col) {
        odbcConnectionColumns(conn, name, column_name = col)
      })
      # use the first match for each field and set up the param_index
      details <- lapply(seq_len(ncol(values)), function(i) {
        if (nrow(details[[i]])) details[[i]][1L,]$param_index <- i
      })
      do.call(rbind, details)
```

So for this PR, I will just fix the missing comma `,`, and let you and @jimhester to decide if need further improvement or not. 

Thanks.

**Comment by jimhester** [comment]
Ok, I am fine with just doing the comma for now, thanks again for the PR @shrektan

**Pull request merged**
